version: "3.8"

services:
  mongodb:
    image: mongo:latest
    hostname: mongo
    container_name: WorkShopPostman
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: