package utils.enums;

public enum TargetEmailToDelete {
	planSetup,
	planPortfolioInvestment, portfolioInvestmentHHInfoAWS, portfolioInvestmentWarningsAWS,
	portfolioInvestmentSidePanelAWS,
	firmDistributionSettings, distributionRoth, distributionOther, distributionTaxable,
	firmDistributionSettingsTraditional, distributionQualifiedRetirement, distributionInherited,
	planPortfolioBanking,
	planPortfolioLifeInsurance,
	planPortfolioOtherAssets,
	planLiabilities,
	planSavings,
	planOtherIncome, otherIncomeTaxTreatment,
	planIncomeSocialSecurity, ssEstimatePrimaryInsurance, ssAllBenefitsMethods,
	planBaselineExpenses,
	planOtherExpenses,
	planRetirementIncomeLegacy,
	planRetirementPowerPlanning,
	incomeScenario,
	lifeHub,
	onlyLifeHub,
	taxLab,
	reportCenter,
	taxSettings,
	mfa,
	modelAllocations, modelAllocationFromHh, modelAllocationFromSettings,
	activateLink,
	resetPassword,
	firm,
	member, firmFlatEditMember, firmFlatDeleteMember, firmFlatCancelMember,
	integrations,
	signUp,
	importHousehold,
	planDashboard,
	adjustmentDashboard,
	balanceDashboard,
	spendingCapacityDashboard,
	accountIncluded, investmentCostBasis
}
