package utils.enums;

public enum TargetPlansToDelete {
	planInfo,
	planPortfolioInvestment,
	portfolioInvestmentHHInfoAWS,
	planPortfolioBanking,
	planPortfolioLifeInsurance,
	planPortfolioOtherAssets,
	planLiabilities,
	planSavings,
	planOtherIncome, otherIncomeTaxTreatment,
	planIncomeSocialSecurity, ssAllBenefitsMethods, ssEstimatePrimaryInsurance,
	planBaselineExpenses,
	planOtherExpenses,
	planRetirementIncomeLegacy,
	planRetirementPowerPlanning,
	incomeScenario,
	lifeHub,
	onlyLifeHub,
	taxLab,
	reportCenter,
	taxSettings,
	planDashboard,
	adjustmentDashboard,
	balanceDashboard,
	spendingCapacityDashboard,
	accountIncluded,
	investmentCostBasis
}
