name: Run Selenium Tests with Allure Reports

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up JDK
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'

    # Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/qa-selenium-workshop/cucumber-archetype-parallel-advance/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Execute tests with custom environment variables
    - name: Execute Tests
      working-directory: /qa-selenium-workshop/cucumber-archetype-parallel-advance
      run: |
        export ENVIRONMENTS=QA
        export PASSWORD=Carolina123.
        export PASSWORD_SUPERADMIN=Carolina123.
        export PLATFORM_GOAL_EXECUTION_TEST=LOCAL
        mvn test -Dcucumber.filter.tags="@Login"

    # Debug: Check features directory
    - name: Debug Check Features Directory
      run: |
        ls -R /qa-selenium-workshop/cucumber-archetype-parallel-advance/src/test/resources/
        ls -R /qa-selenium-workshop/cucumber-archetype-parallel-advance/src/test/java/

    # Generate Allure report
    - name: Generate Allure Report
      working-directory: /qa-selenium-workshop/cucumber-archetype-parallel-advance
      run: mvn io.qameta.allure:allure-maven:2.10.0:report

    # Debug: List files in target directory
    - name: Debug List Files in Target Directory
      run: ls -R /qa-selenium-workshop/cucumber-archetype-parallel-advance/target/

    # Publish Allure Report
    - name: Publish Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: /qa-selenium-workshop/cucumber-archetype-parallel-advance/target/site/allure-report/
