name: Run Selenium Tests with Allure Reports

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin' # Temurin supports JDK 21

    # Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/advance/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

     # Navigate to the specific project folder and run Maven commands
    - name: Run tests and generate Allure report
      run: mvn clean test io.qameta.allure:allure-maven:2.10.0:report
      working-directory: ./advance

    # Publish Allure report
    # Publish Allure report to GitHub Actions artifact
    - name: Publish Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report-${{ github.ref_name }}
        path: ./advance/target/site/allure-report/
